# Site settings
title: Sasha Fedchin
image: /assets/images/profile.jpg
description: This is Sasha Fedchin's personal website. I am a computer scientist with a PhD from Tufts specializing in program verification.

# if you don't have any of social below, comment the line
linkedin: aleksandr-fedchin
github: Dargones
scholar: citations?user=bi4KxZMAAAAJ&hl=en
resume: true

url: https://sasha-fedchin.github.io
baseurl: ""

# Build settings
theme: arco
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
